### ISSUE TITLE
Consider generating `Package.swift` inside KMM module build directory

### ISSUE THREAD

**Issue by kirillzh** [touchlab/KMMBridge#114]
I have an iOS app that wants to depend on a bunch of my KMM modules which are bundled as Swift packages. I would like to use kmmbridge `spm` configuration for that:
```kotlin
kmmbridge {
  spm()
   githubReleaseVersions()
   githubReleaseArtifacts()
}
```

Running `gradle spmDevBuild` on any modules generates a root level `Package.swift` for the latest KMM module that generates Swift package. Could we consider generating `Package.swift` into KMM module's build directory instead of at the root level?

**Comment by carlosmonzon** [comment]
@kirillzh I am running into exactly the same situation.  This is what I tried and the Package.swift file was created in the KMM module directory.

```
 spm(project.projectDir.path)
```

This is path generated in the Package.swift though. 

``` 
path: ".//build/XCFrameworks/debug/\(packageName).xcframework"
```

Instead of dragging and dropping my whole android repo into Xcode, I only dragged and dropped the KMM module and it worked without problems.

@KatieGalvin is this an intended way to use the spm("spmDirectory")?

**Comment by russhwolf** [comment]
@kirillzh  If you're putting the package file in a build directory, you're probably not using the plugin the way we intended. For publishing to work, the package file needs to be checked into the repo.

@carlosmonzon I think what you're doing should work but we haven't tested that sort of flow very much. If it is working we should probably document it better.

**Comment by russhwolf** [comment]
I'm closing this as I don't think it fits the current intended usage of the plugin.

**Comment by fluxxion82** [comment]
@russhwolf I'm trying to generate multiple swift packages in a project with several kmp modules. when using `spm(project.projectDir.path)`, I see individual Package.swift files in the various module as @carlosmonzon pointed out, but like you mentioned, I get an error when we try to publish in the workflow. I get the following error:
```
Run touchlab/autoversion-finishrelease@main
Error: fatal: pathspec './Package.swift' did not match any files
```
Since this isn't the intended usage of the plugin, what is the recommended approach here? Are we supposed to create an 'allShared' module and only publish that for iOS?
