### ISSUE TITLE
Way of managing dependencies on other Swift Packages

### ISSUE THREAD

**Issue by joreilly** [touchlab/KMMBridge#119]
Jut trying this out here and one thing I was wondering was if there was way to manage dependencies on other Swift Packages e.g. KMP-NativeCoroutines....or is expectation that that would always need to be added separately?

**Comment by russhwolf** [comment]
For KMP-NativeCoroutines in particular, I don't think there's a ton of need for this. Unless I misunderstand, you want the KMP-NativeCoroutines Swift package at the app level to use from Swift, but your Kotlin code shouldn't need to reference it. Shared code just needs to reference the Kotlin dependency which you can configure in the usual way.

But I know there's other use-cases for this. The kotlin.cocoapods plugin has functionality for pulling in dependencies and automatically configuring the cinterop for them, but I'm not aware of anything doing that for SPM at the moment. I suspect it would make more sense to add that support in a separate tool rather than here, because it's useful even if you're building Kotlin from source every time and not publishing/consuming binaries.

**Comment by russhwolf** [comment]
In version 0.3.7 you have the option to supply your own package file and KMMBridge will just update the variables that it manages. This should let you add dependencies which will be forwarded to your Xcode project (among other things). See [here](https://kmmbridge.touchlab.co/docs/spm/IOS_SPM#using-a-custom-package-file) for more.

Note that this won't help you talk to any of those dependencies from Kotlin. We do not currently have an SPM equivalent to the way the Cocoapods plugin automatically manages pod dependencies via cinterop.

**Comment by kpgalligan** [comment]
Closing. You can use a custom `Package.swift` file, as Russell discusses here.
