### ISSUE TITLE
Check GITHUB_REPO arg to make sure it's just owner/repo

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#54]
Passing in the whole url, or presumably just the repo and not owner, will result in weird error messages.

The goal is to improve error messaging when an invalid value is passed which informs them that the input must be "Owner/Repo"

Reference: https://touchlab.slack.com/archives/C039SKWFPPW/p1664985641279769

**Comment by samhill303** [comment]
JJ: Not sure what error to catch, not seeing it being thrown. Only see error in http. Should we instead actually validate the format?
RW: It should be fine to validate rather than waiting for an errror
JJ: Which configuration point?
RW: Further down in the flow where you can do both at once if possible, otherwise just check in both

**Comment by samhill303** [comment]
KG: we have a helper function to get the value. If we only validate it after getting the value, future people might forget to validate. So we should be sure to validate it before it gets fetched (in the central helper function, or remove the helper)
