### ISSUE TITLE
[Spike]Multiple framework modules

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#75]
Can we support multiple framework modules in a single repo? What is the current state?
It will probably look different for SPM and cocoapods

Define tasks based on your findings

**Comment by russhwolf** [comment]
3 main things we need here
- github workflow only knows how to build everything, can't build individual modules
- need to think about multimodule SPM config. Cocoapods can have multiple podspecs, but SPM setup assumes a single top-level package file
- think through gradle tasks. Should task names incorporate the module name (eg `kmmBridgeModuleNamePublish`) to disambiguate? Otherwise if you have builds in nested modules you can't tell it which you want to build.
