### ISSUE TITLE
Rename "allshared" to "AllShared" or similar in docs

### ISSUE THREAD

**Issue by TadeasKriz** [touchlab/KMMBridge#87]
This will make the module name consistent with other Swift modules, lowering cognitive load for iOS developers importing the module/reading the code importing it.

**Comment by russhwolf** [comment]
This is a little funny because it's right at the boundary between android and ios convention. Gradle modules are usually lowercase but Swift modules usually use an uppercase name. If you care about both sides of this it probably means you set the frameworkName manually so it's capitalized different from the gradle module.

**Comment by kpgalligan** [comment]
I'm going to close for now, but maybe pull back up later.
